name: Wearipedia DLT Pipeline

on:
  workflow_dispatch: null
  workflow_run:
    workflows: ["Wearipedia to S3 Pipeline"]
    types:
      - completed

env:
  DESTINATION__REDSHIFT__CREDENTIALS__DATABASE: dev
  DESTINATION__REDSHIFT__CREDENTIALS__HOST: redshift-serverless.804373361546.us-east-2.redshift-serverless.amazonaws.com
  DESTINATION__REDSHIFT__CREDENTIALS__PORT: '5439'
  DESTINATION__REDSHIFT__CREDENTIALS__USERNAME: ${{ secrets.REDSHIFT_USER }}
  DESTINATION__REDSHIFT__CREDENTIALS__PASSWORD: ${{ secrets.DESTINATION__REDSHIFT__CREDENTIALS__PASSWORD }}
  # SOURCES__CREDENTIALS__AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # SOURCES__CREDENTIALS__AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # DESTINATION__FILESYSTEM__CREDENTIALS__AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # DESTINATION__FILESYSTEM__CREDENTIALS__AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # SOURCES__READERS__FILESYSTEM__CREDENTIALS__AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # SOURCES__READERS__FILESYSTEM__CREDENTIALS__AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # DESTINATION__FILESYSTEM__BUCKET_URL: ${{ secrets.WEARIPEDIA_S3_BUCKET_NAME }}
  # SOURCES__BUCKET_URL: ${{ secrets.WEARIPEDIA_S3_BUCKET_NAME }}
  NORMALIZE__LOADER_FILE_FORMAT: parquet

jobs:
  run-dlt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dlt_normalization/requirements_dlt.txt

      - name: Run DLT Pipeline
        run: python wearipedia/wearipedia_to_db_pipeline.py
